### ISSUE TITLE
启动报错了

### ISSUE THREAD

**Issue by levylll** [SD-Gaming/Vue2.0_to_do_list-addName-#1]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue_addname@1.0.0~predev: vue_addname@1.0.0
6 info lifecycle vue_addname@1.0.0~dev: vue_addname@1.0.0
7 verbose lifecycle vue_addname@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue_addname@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lailong/levy/DYD/frontend/Vue2.0_to_do_list-addName-/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle vue_addname@1.0.0~dev: CWD: /Users/lailong/levy/DYD/frontend/Vue2.0_to_do_list-addName-
10 silly lifecycle vue_addname@1.0.0~dev: Args: [ '-c', 'node build/dev-server.js' ]
11 silly lifecycle vue_addname@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle vue_addname@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: vue_addname@1.0.0 dev: `node build/dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid vue_addname@1.0.0
15 verbose cwd /Users/lailong/levy/DYD/frontend/Vue2.0_to_do_list-addName-
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.4.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue_addname@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vue_addname@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.

另外，您的视频好像看不了了。请问还有哪里可以看，多谢了。

**Comment by qiaojianjunjojo** [comment]
https://www.imooc.com/video/16408
